app:
  SPOTIFY_CLIENT_ID: "7ac1581442ee4259a92384eb950467a9"
  SPOTIFY_CLIENT_SECRET: "47e984fcc34447cfa5c42a87d4274dea"
  GOOGLE_MAPS_API_KEY: "AIzaSyCMy-hZqtoVsrPPMxN18Y0anKZQBqYHt7Q"
  OPENROUTE_API_KEY: "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjZlOGM3ZGNlMGI4ZjRkN2ZhM2I1ZjM3OTNlMDU3ZWY0IiwiaCI6Im11cm11cjY0In0="
api:
  lala: "lala"